### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by moiSentineL** [AniketBhatikarCreations/aniketbhatikarcreations.github.io#2]
Rename your repo to `aniketbhatikarcreations.github.io`. This removes the `/abc` page and people can access your website by `https://aniketbhatikarcreations.github.io/` only.

**Comment by AniketBhatikarCreations** [comment]
Yeah!! Thx for the info🙏

**Comment by AniketBhatikarCreations** [comment]
Yes! I updated 👍
